require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CompletedAssignmentsController do

  # This should return the minimal set of attributes required to create a valid
  # CompletedAssignment. As you add validations to CompletedAssignment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CompletedAssignmentsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all completed_assignments as @completed_assignments" do
      completed_assignment = CompletedAssignment.create! valid_attributes
      get :index, {}, valid_session
      assigns(:completed_assignments).should eq([completed_assignment])
    end
  end

  describe "GET show" do
    it "assigns the requested completed_assignment as @completed_assignment" do
      completed_assignment = CompletedAssignment.create! valid_attributes
      get :show, {:id => completed_assignment.to_param}, valid_session
      assigns(:completed_assignment).should eq(completed_assignment)
    end
  end

  describe "GET new" do
    it "assigns a new completed_assignment as @completed_assignment" do
      get :new, {}, valid_session
      assigns(:completed_assignment).should be_a_new(CompletedAssignment)
    end
  end

  describe "GET edit" do
    it "assigns the requested completed_assignment as @completed_assignment" do
      completed_assignment = CompletedAssignment.create! valid_attributes
      get :edit, {:id => completed_assignment.to_param}, valid_session
      assigns(:completed_assignment).should eq(completed_assignment)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CompletedAssignment" do
        expect {
          post :create, {:completed_assignment => valid_attributes}, valid_session
        }.to change(CompletedAssignment, :count).by(1)
      end

      it "assigns a newly created completed_assignment as @completed_assignment" do
        post :create, {:completed_assignment => valid_attributes}, valid_session
        assigns(:completed_assignment).should be_a(CompletedAssignment)
        assigns(:completed_assignment).should be_persisted
      end

      it "redirects to the created completed_assignment" do
        post :create, {:completed_assignment => valid_attributes}, valid_session
        response.should redirect_to(CompletedAssignment.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved completed_assignment as @completed_assignment" do
        # Trigger the behavior that occurs when invalid params are submitted
        CompletedAssignment.any_instance.stub(:save).and_return(false)
        post :create, {:completed_assignment => { "user" => "invalid value" }}, valid_session
        assigns(:completed_assignment).should be_a_new(CompletedAssignment)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CompletedAssignment.any_instance.stub(:save).and_return(false)
        post :create, {:completed_assignment => { "user" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested completed_assignment" do
        completed_assignment = CompletedAssignment.create! valid_attributes
        # Assuming there are no other completed_assignments in the database, this
        # specifies that the CompletedAssignment created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CompletedAssignment.any_instance.should_receive(:update_attributes).with({ "user" => "" })
        put :update, {:id => completed_assignment.to_param, :completed_assignment => { "user" => "" }}, valid_session
      end

      it "assigns the requested completed_assignment as @completed_assignment" do
        completed_assignment = CompletedAssignment.create! valid_attributes
        put :update, {:id => completed_assignment.to_param, :completed_assignment => valid_attributes}, valid_session
        assigns(:completed_assignment).should eq(completed_assignment)
      end

      it "redirects to the completed_assignment" do
        completed_assignment = CompletedAssignment.create! valid_attributes
        put :update, {:id => completed_assignment.to_param, :completed_assignment => valid_attributes}, valid_session
        response.should redirect_to(completed_assignment)
      end
    end

    describe "with invalid params" do
      it "assigns the completed_assignment as @completed_assignment" do
        completed_assignment = CompletedAssignment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CompletedAssignment.any_instance.stub(:save).and_return(false)
        put :update, {:id => completed_assignment.to_param, :completed_assignment => { "user" => "invalid value" }}, valid_session
        assigns(:completed_assignment).should eq(completed_assignment)
      end

      it "re-renders the 'edit' template" do
        completed_assignment = CompletedAssignment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CompletedAssignment.any_instance.stub(:save).and_return(false)
        put :update, {:id => completed_assignment.to_param, :completed_assignment => { "user" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested completed_assignment" do
      completed_assignment = CompletedAssignment.create! valid_attributes
      expect {
        delete :destroy, {:id => completed_assignment.to_param}, valid_session
      }.to change(CompletedAssignment, :count).by(-1)
    end

    it "redirects to the completed_assignments list" do
      completed_assignment = CompletedAssignment.create! valid_attributes
      delete :destroy, {:id => completed_assignment.to_param}, valid_session
      response.should redirect_to(completed_assignments_url)
    end
  end

end
